version: '3.8'

services:
  backend_python:
    image: quangvinh1601/jlearn_be_python_app:latest
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    external: true
